Extend `une possibilité`
publicodes/publicodes pull request #597
Opened 2024-11-20 15:40 UTC by johangirod

- `une possibilité` now accepts inlined rule and constant
- All possibilities are parsed and added to the rule node under the key
  `possibleChoices`
- Add a strict option to checks if the evaluated value is in the list of
  possible choices and throws an error if not
- Add a warning when using the deprecated key `une possibilité` inside
  the `valeur` key
- Remove the `une possibilité` mecanism (it was not a real mecanism)
- Add doc and test
- improve type inference

[Go to documentation page](https://deploy-preview-597--publicodes-website.netlify.app/docs/manuel/une-possibilit%C3%A9)

Todo : 
- [x] Add 'une possibilité' section in documentation
- [x] Add 'une possibilité' view in autogenerated explanations

2024-12-17 14:31 UTC, EmileRolley requested changes
Trop bien d'enfin se saisir de ce sujet, merci !

Je trouve que c'est bien dans l'ensemble, il reste néanmoins de la place pour plus d'explications sur la syntaxe et la sémantique je pense. Notamment sur la gestion des références dans les possibilités.

2024-12-17 14:31 UTC, EmileRolley commented on packages/core/src/rule.ts
> +	}
```suggestion
	let possibleChoices = parsePossibleChoices(context, rawRule)
```

2024-12-17 14:31 UTC, EmileRolley commented on packages/core/src/rule.ts
> +		;[possibleChoices, avec] = parseChoixPossibles(
question: c'est quoi cette syntaxe `let <id>; [<id>]` ?

2024-12-17 14:31 UTC, EmileRolley commented on packages/core/src/rule.ts
> +		possibleChoices,
question: on est d'accord qu'à présent pour tester si une règle est une définition de possibilités il faudra faire `engine.getRule(name).possibleChoices !== null` ?

2024-12-17 14:31 UTC, EmileRolley commented on packages/core/test/parseExpression.test.ts
> -			unité: '/c/d/e',
question: pourquoi supprimer ces tests ?

2024-12-17 14:31 UTC, EmileRolley commented on packages/core/src/rule.ts
> +		if (typeof formule === 'object' && formule['une possibilité']) {
question 2: on est d'accord que la syntaxe ne sera plus prise en compte maintenant ? Est-ce que l'on souhaite pas la garder avec un warning ?

```yaml
  une possibilité:
    possibilités:
      - mécanique simple
      - électrique
      - cargo
      - cargo électrique
```

2024-12-17 14:31 UTC, EmileRolley commented on packages/core/test/unePossibilité.test.js
> +  par défaut: "'d'"
question: est-ce que l'on a pas envie d'introduire la possibilité d'utiliser une référence directement `par défaut: d` ?

2024-12-17 14:31 UTC, EmileRolley commented on packages/core/test/unePossibilité.test.js
> +})
remarque: il manque un test pour le cas :

```yaml
a: 
  une possibilité:
    - b
    - c
  par défaut: "'b'"
```

D'ailleurs est-ce que l'on a envie que ça lève une exception ou est-ce que l'on veut définir les règles référencées au parsing ? Dans le quel cas, on pourrait leur donner des valeurs par défaut ce qui permettrait d'utiliser les références plutôt que les constantes, (ce qui n'a plus trop de sens avec la nouvelle syntaxe d'ailleurs).

2024-12-17 14:31 UTC, EmileRolley commented on packages/core/test/unePossibilité.test.js
> +			expect(engine.evaluate('a . a').nodeValue).to.equal(true)
question!: pourquoi l'évaluation de `a . a` devrait être égale à `true` ici ?

2024-12-17 14:31 UTC, EmileRolley commented on website/src/routes/docs/manuel/une-possibilité/+page.svelte.md
> +A noter, les unités sont optionnelles dans les possibilités de nombres. Si elles sont présentes, elles doivent être cohérentes entre elles.
```suggestion
A noter, les unités sont optionnelles dans les possibilités de nombres. Si elles sont présentes, elles doivent être cohérentes entre elles (càd. elles doivent toutes être simplifiable en une même unité).
```

2024-12-17 14:31 UTC, EmileRolley commented on website/src/routes/docs/manuel/une-possibilité/+page.svelte.md
> +
question: est-ce que les possibilités doivent nécessairement être des références vers des règles filles directes ? Que se passe-t-il si une règle se référence elle-même dans ses possibilités ?

2024-12-17 14:31 UTC, EmileRolley commented on website/src/routes/docs/manuel/une-possibilité/+page.svelte.md
> +const possibleValues: ASTNode[] | undefined = contrat.possibleValues;
remarque: ça devrait être un tableau de `RuleNode` et non pas d'`ASTNode` non ?

2024-12-17 16:22 UTC, johangirod commented on packages/core/src/inferNodeType.ts
> +						}
+ Expliciter que les possibilités forcent le type de la règle...

2024-12-17 16:27 UTC, johangirod commented on packages/core/src/parseChoixPossibles.ts
> +export function parseChoixPossibles(
Unifier

2024-12-17 16:28 UTC, johangirod commented on packages/core/src/parseChoixPossibles.ts
> +	avec: Record<string, Rule>,
Retourner un objet, et documenter.

2024-12-18 15:07 UTC, johangirod commented on packages/core/test/unePossibilité.test.js
> +})
Tu suggère de ne pas créer automatiquement les règles dans ce cas... intéressant ! Je suis plutôt pour. Dans ce cas on pourrait effectivement ne pas utiliser la syntaxe `inline` et ne pas pouvoir définir des constantes de type string.

2024-12-18 15:10 UTC, johangirod commented on packages/core/test/unePossibilité.test.js
> +  par défaut: "'d'"
Pas possible. Il faut qu'il soit possible de calculer cette valeur (par exemple une variation).

2024-12-19 09:06 UTC, johangirod commented on packages/core/test/unePossibilité.test.js
> +			expect(engine.evaluate('a . a').nodeValue).to.equal(true)
J'ai enlevé ce comportement

2024-12-19 09:18 UTC, johangirod commented on website/src/routes/docs/manuel/une-possibilité/+page.svelte.md
> +
> est-ce que les possibilités doivent nécessairement être des références vers des règles filles directes ?

Je dirai non, notamment car cela ouvre la porte à pouvoir "copier" les possibilités d'une règle à l'autre, ce qui est une bonne chose.

> Que se passe-t-il si une règle se référence elle-même dans ses possibilités ?

Je ne vois pas de problème à ce que ce soit autorisé même si ça n'a pas beaucoup de sens.

2024-12-19 09:37 UTC, EmileRolley commented on packages/core/test/unePossibilité.test.js
> +})
Je ne vois pas le problème, soit tu parse `a . b` en premier et dans ce cas là tu créer la règle `a . b . c` avec des champs par défaut (en l'occurrence uniquement un `valeur: "'c'"` et quand tu parse ensuite `b . c` tu écrase les mécanismes. Et l'autre sens fonctionne également.

2024-12-19 14:36 UTC, johangirod commented on packages/core/test/unePossibilité.test.js
> +})
> `et quand tu parse ensuite b . c tu écrase les mécanismes`

C'est la le problème, aujourd'hui dans publicodes on ne peut pas déclarer une règle deux fois, et il n'existe pas d'option pour « écraser » une règle existante. Ça pourrait être une fonctionalité intéressante (notamment pour les import, ou l'on pourrait ainsi venir écraser certains champs). Mais hors du scope de cette PR.

2024-12-20 14:26 UTC, closed without merging